repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: semgrep-local
        name: Semgrep Custom Security Scan
        entry: .venv/bin/semgrep scan --config=.semgrep/rules.yaml --error
        language: system
        types: [python]
        pass_filenames: false
